version: '3.8'

services:
  mongodb:
    image: mongo:7.0.7
    container_name: cabinet-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - cabinet-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  backend:
    image: ghcr.io/abdelfattehsakkat/cabinet-backend:latest
    container_name: cabinet-backend
    ports:
      - "3000:3000"
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb://root:password@mongodb:27017/cabinetdb?authSource=admin
      - JWT_SECRET=your_jwt_secret_key_here
      - JWT_EXPIRE=1d
      - UPLOAD_DIR=./uploads
    networks:
      - cabinet-network

  frontend:
    image: ghcr.io/abdelfattehsakkat/cabinet-frontend:latest
    container_name: cabinet-frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - cabinet-network
    volumes:
      # Monte un config.json personnalisé depuis l'hôte (adapter le chemin si besoin)
      - /home/cabinetapp/cabinet-manager/config/config.json:/usr/share/nginx/html/assets/config.json:ro

networks:
  cabinet-network:
    driver: bridge

volumes:
  mongodb_data:
